# Generated by Django 3.0.3 on 2020-02-29 19:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Prac1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='Color',
            new_name='pcolor',
        ),
        migrations.AddField(
            model_name='color',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 29, 19, 43, 24, 309429, tzinfo=utc), verbose_name='date published'),
        ),
    ]
