# Generated by Django 3.0.3 on 2020-02-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prac1', '0003_auto_20200301_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='pub_date',
            field=models.DateTimeField(default=0, verbose_name='date published'),
        ),
    ]
